(()=>{const input=document.getElementById('scopeQuery'),btn=document.getElementById('scopeBtn'),out=document.getElementById('scopeResult');if(!input||!btn||!out)return;
const rows=[
{patterns:["0102","live cattle","cattle"],commodity:"Cattle",status:"review",title:"Potential EUDR cattle product",detail:"The 2026 Annex I uses ex 0102 and limits the cattle commodity to specified Bos genera. Confirm species and exact CN classification."},
{patterns:["0201","0202","beef","bovine meat"],commodity:"Cattle",status:"review",title:"Likely cattle-related Annex I match",detail:"Specified cattle meat products are listed. Confirm the exact CN code and species limitation."},
{patterns:["02062100","0206 21 00","frozen cattle tongue","frozen cattle tongues"],commodity:"Cattle",status:"future",title:"Added from 30 December 2027",detail:"Frozen cattle tongues under ex 0206 21 00 were added by the 2026 update and become subject from 30 December 2027."},
{patterns:["4101","4104","4107","cattle leather","bovine leather","raw cattle hides","cattle hides"],commodity:"Cattle",status:"out",title:"Removed from Annex I in 2026",detail:"The cattle entries for 4101, 4104 and 4107 were deleted by Delegated Regulation (EU) 2026/2102."},
{patterns:["1801","1802","1803","1804","1805","1806","cocoa","chocolate"],commodity:"Cocoa",status:"in",title:"Likely cocoa-related Annex I match",detail:"Cocoa and specified cocoa products are covered. Waste exclusions and exact product classification can matter."},
{patterns:["0901","coffee bean","coffee beans","roasted coffee","green coffee"],commodity:"Coffee",status:"in",title:"Likely coffee Annex I match",detail:"Coffee under heading 0901 is a core EUDR product group. Confirm the exact CN code."},
{patterns:["21011100","2101 11 00","soluble coffee","instant coffee","coffee extract"],commodity:"Coffee",status:"future",title:"Added from 30 December 2027",detail:"Extracts, essences and concentrates of coffee (2101 11 00) were added by the 2026 update and apply from 30 December 2027."},
{patterns:["120710","1207 10","1511","151321","151329","palm oil","palm kernel"],commodity:"Oil palm",status:"review",title:"Potential oil-palm Annex I match",detail:"Oil-palm entries often use “ex” wording and may depend on whether the product was made using Elaeis spp. Confirm composition and exact CN code."},
{patterns:["151620","1516 20","151800","1518 00","152000","1520 00","290516","290517","290519","291615","29161910","292119","29239000","29241900","34011100","340120","382499","390729","palm derivative","palm oleochemical"],commodity:"Oil palm",status:"future",title:"2027 oil-palm derivative entry",detail:"The 2026 update added a range of specified oil-palm derivatives. Many are “ex” entries and apply from 30 December 2027; confirm the exact legal wording."},
{patterns:["4001","natural rubber","latex"],commodity:"Rubber",status:"in",title:"Likely natural-rubber Annex I match",detail:"Natural rubber is a core EUDR commodity. Confirm species (Hevea brasiliensis) and exact code."},
{patterns:["4012","retread tyre","retreaded tyre","retread tire","retreaded tire"],commodity:"Rubber",status:"out",title:"Retreaded tyres removed/narrowed in 2026",detail:"The 2026 update removed retreaded tyres from the prior broad 4012 treatment and narrowed the remaining relevant entry. Verify the exact subheading."},
{patterns:["4010","conveyor belt","transmission belt","4016","vulcanised rubber articles","vulcanized rubber articles"],commodity:"Rubber",status:"out",title:"Specified rubber articles removed in 2026",detail:"The 2026 update removed several downstream vulcanised-rubber entries, including conveyor/transmission belts and specified articles."},
{patterns:["120110","1201 10","soybean seed","soybeans for sowing"],commodity:"Soy",status:"out",title:"Soybeans for sowing removed in 2026",detail:"Soybeans for sowing were removed from the EUDR Annex I scope by the 2026 update."},
{patterns:["1201","120190","1208","1507","2304","soy","soya","soybean"],commodity:"Soy",status:"in",title:"Likely soy Annex I match",detail:"Soy and specified soy-derived products are covered. Confirm the precise subheading and that the product is not an excluded sowing seed entry."},
{patterns:["4401","4402","4403","4404","4405","4406","4407","4408","4409","4410","4411","4412","4413","4414","4415","4416","4417","4418","4419","4420","4421","timber","lumber","plywood","wooden furniture","wood furniture","paper","pulp"],commodity:"Wood",status:"review",title:"Potential wood Annex I match",detail:"Wood coverage spans many headings and specified downstream products. Bamboo, rattan and certain other woody materials are excluded from the wood commodity definition; confirm exact code and material."},
{patterns:["940330","940340","940350","940360","wooden seat","wooden furniture"],commodity:"Wood",status:"review",title:"Potential wood-derived product match",detail:"Specified wooden furniture products can fall within Annex I. Confirm the exact CN code and material composition."}
];
const labels={in:"Likely in scope",review:"Review “ex” / exact code",future:"Added from 30 Dec 2027",out:"Removed / excluded"};
function norm(v){return v.toLowerCase().replace(/[.\-_/]/g," ").replace(/\s+/g," ").trim()}
function check(){const raw=input.value.trim();if(!raw){out.innerHTML='<div class="empty"><b>Enter a code or product</b></div>';return}const q=norm(raw),digits=raw.replace(/\D/g,"");let matches=rows.filter(r=>r.patterns.some(p=>{const np=norm(p),pd=p.replace(/\D/g,"");return q.includes(np)||np.includes(q)||(digits.length>=4&&pd.length>=4&&(digits.startsWith(pd)||pd.startsWith(digits)))}));if(!matches.length){out.innerHTML='<span class="scopeTag review">Manual review needed</span><h3>No high-confidence local match</h3><p>We did not find this term in the current built-in screening dataset. That does <b>not</b> mean the product is outside EUDR. Check the exact CN code against the current Annex I.</p><div class="resultActions"><a href="/commodities/">Browse commodity scope →</a><a href="/report/">Generate EUDR report →</a><a href="https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:32026R2102" target="_blank">Open official 2026 update ↗</a></div>';return}const best=matches[0];out.innerHTML='<span class="scopeTag '+best.status+'">'+labels[best.status]+'</span><div class="eyebrow" style="margin-top:16px">'+best.commodity+'</div><h3>'+best.title+'</h3><p>'+best.detail+'</p><div class="scopeMeta"><div><span>Search</span><b>'+esc(raw)+'</b></div><div><span>Result type</span><b>'+labels[best.status]+'</b></div></div><div class="resultActions"><a href="/commodities/'+slug(best.commodity)+'/">Open '+best.commodity+' guide →</a><a href="/#checker">Run full preliminary checker →</a><a href="/report/">Generate EUDR report →</a><a href="https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:32026R2102" target="_blank">Verify official Annex update ↗</a></div><p class="toolDisclaimer">Preliminary screening only. “ex” entries cover only part of a CN heading and can depend on species, material or how a product was made.</p>'}
function slug(v){return({"Cattle":"cattle","Cocoa":"cocoa","Coffee":"coffee","Oil palm":"oil-palm","Rubber":"rubber","Soy":"soy","Wood":"wood"})[v]||""}
function esc(v){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
btn.addEventListener("click",check);input.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();check()}});document.querySelectorAll("[data-q]").forEach(x=>x.addEventListener("click",()=>{input.value=x.dataset.q;check()}));
})();