(()=>{const form=document.getElementById("reportForm"),out=document.getElementById("reportOutput"),buy=document.getElementById("paypalBuy"),status=document.getElementById("paymentStatus");if(!form||!out)return;
const cfg=window.EUDR_PAYMENT||{},link=cfg.professionalReport||"";if(buy&&link){buy.href=link;buy.classList.remove("disabledLink");if(status)status.textContent="Secure one-time payment via PayPal. Professional report delivery follows payment confirmation."}else if(buy){buy.addEventListener("click",e=>e.preventDefault())}
const fields=['companyName','reportRole','reportSize','reportProduct','reportCode','reportCommodity','reportCountry','reportRisk','reportGeo','reportEvidence','reportNotes'];
fields.forEach(id=>{const el=document.getElementById(id);if(!el)return;const saved=localStorage.getItem('eudr_report_'+id);if(saved!==null)el.value=saved;el.addEventListener('input',()=>localStorage.setItem('eudr_report_'+id,el.value))});
form.addEventListener("submit",e=>{e.preventDefault();const v=id=>document.getElementById(id).value.trim(),company=v("companyName"),role=v("reportRole"),size=v("reportSize"),product=v("reportProduct"),code=v("reportCode"),commodity=v("reportCommodity"),country=v("reportCountry"),risk=v("reportRisk"),geo=v("reportGeo"),evidence=v("reportEvidence"),notes=v("reportNotes");
const deadline=size==="small"?"30 June 2027":"30 December 2026";
const gaps=[];let readiness=20;
if(code)readiness+=15;else gaps.push("Exact CN / HS code has not been entered.");
if(risk!=="unknown"){readiness+=15}else gaps.push("Country risk classification still needs to be checked.");
if(geo==="Collected and validated"){readiness+=25}else if(geo==="Collected but not validated"){readiness+=12;gaps.push("Geolocation data is collected but still needs validation.")}else gaps.push("Geolocation evidence is not yet fully collected and validated.");
if(evidence==="Complete"){readiness+=25}else if(evidence==="Partially complete"){readiness+=12;gaps.push("Supplier evidence package is only partially complete.")}else gaps.push("Supplier evidence package is not yet complete.");
const riskText=risk==="low"?"Low-risk origin may support simplified due diligence when all legal conditions are met, but required information still needs to be collected.":risk==="standard"?"Standard-risk origin should be treated as requiring the normal due-diligence risk assessment unless another rule applies.":risk==="high"?"High-risk origin warrants particular attention to evidence quality, risk assessment and mitigation.":"Risk classification must be confirmed before relying on the workflow.";
const readinessLabel=readiness>=80?"Advanced preparation":readiness>=60?"Moderate preparation":"Material gaps remain";
const article9=[["Product description & commodity",product&&commodity],["Quantity / transaction data",false],["Country of production",country],["Geolocation",geo==="Collected and validated"],["Supplier / customer details",evidence==="Complete"],["Deforestation-free evidence",evidence==="Complete"],["Legality evidence",evidence==="Complete"]];
const article9Done=article9.filter(x=>x[1]).length;
out.innerHTML='<article id="printReport" class="printReport"><div class="reportHeader"><div><span class="eyebrow">EUDR screening report</span><h2>'+esc(company)+'</h2><p>'+esc(product)+(code?' • CN/HS '+esc(code):'')+'</p></div><div class="reportStamp">Generated<br>'+new Date().toLocaleDateString()+'</div></div>'+
'<div class="readinessBlock"><div><span>Preparation score</span><strong>'+readiness+'%</strong><small>'+readinessLabel+'</small></div><div class="readinessTrack"><i style="width:'+readiness+'%"></i></div><p>This is a workflow-readiness indicator only, not a legal compliance score or certification.</p></div>'+
'<div class="reportSummary"><div><span>Commodity</span><b>'+esc(commodity)+'</b></div><div><span>Role</span><b>'+esc(role)+'</b></div><div><span>Production country</span><b>'+esc(country)+'</b></div><div><span>Country risk</span><b>'+esc(risk)+'</b></div><div><span>Geolocation</span><b>'+esc(geo)+'</b></div><div><span>Application date</span><b>'+deadline+'</b></div></div>'+
'<h3>Executive summary</h3><p>This preliminary assessment indicates that the transaction should continue through product-scope confirmation, Article 9 information collection and the applicable risk-assessment workflow before any DDS or simplified declaration step is treated as complete.</p><p>'+riskText+'</p>'+
'<h3>Article 9 information snapshot</h3><div class="miniChecklist">'+article9.map(([name,ok])=>'<div class="'+(ok?'done':'gap')+'"><span>'+(ok?'✓':'!')+'</span><b>'+esc(name)+'</b></div>').join("")+'</div><p>'+article9Done+' of '+article9.length+' core information categories appear addressed from the current form inputs.</p>'+
'<h3>Evidence gaps</h3>'+(gaps.length?'<ul>'+gaps.map(x=>'<li>'+esc(x)+'</li>').join("")+'</ul>':'<p>No major gaps were indicated in the current form. Underlying records still need to be verified for accuracy, reliability and completeness.</p>')+
'<h3>Recommended action plan</h3><ol><li>Confirm exact Annex I scope and CN classification.</li><li>Complete Article 9 information collection, including quantity, supplier/customer details and required production data.</li><li>Validate all required plot or establishment geolocation.</li><li>Assess reliability, legality and deforestation-free evidence.</li><li>Apply Article 10 risk assessment criteria where required, including supply-chain complexity and origin-specific concerns.</li><li>Document Article 11 mitigation measures if risk is more than negligible.</li><li>Prepare the applicable DDS or simplified declaration workflow.</li><li>Retain required records for the applicable five-year period.</li></ol>'+
(notes?'<h3>Notes</h3><p>'+esc(notes)+'</p>':'')+
'<h3>Official sources</h3><ul class="sourceList"><li><a href="https://green-forum.ec.europa.eu/nature-and-biodiversity/deforestation-regulation-implementation/understand-due-diligence_en" target="_blank" rel="noopener">European Commission — Understand due diligence ↗</a></li><li><a href="https://green-forum.ec.europa.eu/countries-and-partnerships/country-classification-list_en" target="_blank" rel="noopener">European Commission — Country classification ↗</a></li><li><a href="https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02023R1115-20251226" target="_blank" rel="noopener">EUR-Lex — consolidated EUDR text ↗</a></li></ul>'+
'<p class="toolDisclaimer">This report is a preliminary compliance aid and does not constitute legal advice, a DDS, or certification of compliance.</p></article>'+
'<section class="proPreview"><div class="eyebrow">Professional report preview</div><h3>What the €49 version adds</h3><div class="proPreviewGrid"><div><b>Scope Assessment</b><p>Structured product/CN review and assumptions.</p></div><div><b>Risk Matrix</b><p>Origin, evidence and supply-chain risk factors.</p></div><div><b>Evidence Gap Analysis</b><p>Article 9 data gaps grouped by priority.</p></div><div><b>Supplier Evidence Section</b><p>Supplier data and geolocation readiness.</p></div><div><b>Action Plan</b><p>Prioritized next actions before DDS workflow.</p></div><div><b>Professional Layout</b><p>Client-ready report delivery after payment confirmation.</p></div></div><a class="btn primary" href="'+(link||'/pricing/')+'" '+(link?'target="_blank" rel="noopener"':'')+'>Get Professional Report — €49</a><a class="sampleLink" href="/professional-report-sample/">View sample Professional report →</a></section>'+
'<div class="reportActions"><button id="printReportBtn" class="btn secondary">Print / Save as PDF</button><button id="copyReportBtn" class="btn secondary">Copy report summary</button><a class="btn primary" href="/pricing/">Pricing</a></div>';
document.getElementById("printReportBtn")?.addEventListener("click",()=>window.print());document.getElementById("copyReportBtn")?.addEventListener("click",async()=>{const text=document.getElementById("printReport").innerText;try{await navigator.clipboard.writeText(text);document.getElementById("copyReportBtn").textContent="Copied"}catch(err){}});out.scrollIntoView({behavior:"smooth",block:"start"})});
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}})();